/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EspeThemeToggle {
        /**
          * @default 'light'
         */
        "initialTheme": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface EspeThemeToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEspeThemeToggleElement;
}
declare global {
    interface HTMLEspeThemeToggleElementEventMap {
        "themeChanged": string;
    }
    interface HTMLEspeThemeToggleElement extends Components.EspeThemeToggle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEspeThemeToggleElementEventMap>(type: K, listener: (this: HTMLEspeThemeToggleElement, ev: EspeThemeToggleCustomEvent<HTMLEspeThemeToggleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEspeThemeToggleElementEventMap>(type: K, listener: (this: HTMLEspeThemeToggleElement, ev: EspeThemeToggleCustomEvent<HTMLEspeThemeToggleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEspeThemeToggleElement: {
        prototype: HTMLEspeThemeToggleElement;
        new (): HTMLEspeThemeToggleElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "espe-theme-toggle": HTMLEspeThemeToggleElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface EspeThemeToggle {
        /**
          * @default 'light'
         */
        "initialTheme"?: string;
        "onThemeChanged"?: (event: EspeThemeToggleCustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "espe-theme-toggle": EspeThemeToggle;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "espe-theme-toggle": LocalJSX.EspeThemeToggle & JSXBase.HTMLAttributes<HTMLEspeThemeToggleElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
